export const generateInvoice = async (data) => {
  const requestBody = {
    companyVatCode: process.env.BUSINESS_CIF,
    client: {
      name: "Intelligent IT",
      vatCode: "RO12345678",
      address: "str. Sperantei, nr. 5",
      isTaxPayer: false,
      city: "Sibiu",
      county: "Sibiu",
      country: "Romania",
      saveToDb: false,
    },
    isDraft: false,
    issueDate: "2021-02-19",
    seriesName: "FCT",
    currency: "RON",
    language: "RO",
    precision: 2,
    dueDate: "2021-03-28",
    useEstimateDetails: false,
    estimate: {
      seriesName: "PFCT",
      number: "0203",
    },
    products: [
      {
        name: "Mapa A4",
        code: "ccd1",
        productDescription: "produse de papetarie",
        isDiscount: false,
        measuringUnitName: "buc",
        currency: "RON",
        quantity: 2,
        price: 40,
        isTaxIncluded: true,
        taxName: "Normala",
        taxPercentage: 19,
        saveToDb: false,
        isService: false,
      },
    ],
  };
};

const invoiceBody = {
  companyVatCode: "RO12345678",
  client: {
    name: "Intelligent IT",
    vatCode: "RO12345678",
    address: "str. Sperantei, nr. 5",
    isTaxPayer: false,
    city: "Sibiu",
    county: "Sibiu",
    country: "Romania",
    saveToDb: false,
  },
  isDraft: false,
  issueDate: "2021-02-19",
  seriesName: "FCT",
  currency: "RON",
  language: "RO",
  precision: 2,
  dueDate: "2021-03-28",
  useEstimateDetails: false,
  estimate: {
    seriesName: "PFCT",
    number: "0203",
  },
  products: [
    {
      name: "Mapa A4",
      code: "ccd1",
      productDescription: "produse de papetarie",
      isDiscount: false,
      measuringUnitName: "buc",
      currency: "RON",
      quantity: 2,
      price: 40,
      isTaxIncluded: true,
      taxName: "Normala",
      taxPercentage: 19,
      saveToDb: false,
      isService: false,
    },
    {
      name: "Biblioraft Plastifiat",
      code: "ccd2",
      productDescription: "produse de papetarie",
      isDiscount: false,
      measuringUnitName: "buc",
      currency: "RON",
      quantity: 3,
      price: 60,
      isTaxIncluded: true,
      taxName: "Normala",
      taxPercentage: 19,
      saveToDb: false,
      isService: false,
    },
    {
      name: "Discount valoric pe produsul 2",
      isDiscount: true,
      numberOfItems: 1,
      measuringUnitName: "buc",
      currency: "RON",
      isTaxIncluded: true,
      taxName: "Normala",
      taxPercentage: 19,
      discountType: 1,
      discountValue: -15,
    },
    {
      name: "Discount procentual pe produsul 1, 2 si 3",
      isDiscount: true,
      numberOfItems: 3,
      measuringUnitName: "buc",
      currency: "RON",
      isTaxIncluded: true,
      taxName: "Normala",
      taxPercentage: 19,
      discountType: 2,
      discountPercentage: 10,
    },
  ],
  payment: {
    value: 100,
    type: "Ordin plata",
    isCash: false,
  },
};
