/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        backgroundPrimary: "var(--background-primary)",
        backgroundPrimary90: "var(--background-primary-90)",
        backgroundPrimary80: "var(--background-primary-80)",
        backgroundPrimary70: "var(--background-primary-70)",
        backgroundPrimary60: "var(--background-primary-60)",
        backgroundPrimary50: "var(--background-primary-50)",
        backgroundPrimary40: "var(--background-primary-40)",
        backgroundPrimary30: "var(--background-primary-30)",
        backgroundPrimary20: "var(--background-primary-20)",
        backgroundPrimary10: "var(--background-primary-10)",
        backgroundPrimary0 : "var(--background-primary-0)",

        backgroundSecondary: "var(--background-secondary)",
        backgroundSecondary90: "var(--background-secondary-90)",
        backgroundSecondary80: "var(--background-secondary-80)",
        backgroundSecondary70: "var(--background-secondary-70)",
        backgroundSecondary60: "var(--background-secondary-60)",
        backgroundSecondary50: "var(--background-secondary-50)",
        backgroundSecondary40: "var(--background-secondary-40)",
        backgroundSecondary30: "var(--background-secondary-30)",
        backgroundSecondary20: "var(--background-secondary-20)",
        backgroundSecondary10: "var(--background-secondary-10)",
        backgroundSecondary0 : "var(--background-secondary-0)",

        foregroundPrimary: "var(--foreground-primary)",
        foregroundPrimary90: "var(--foreground-primary-90)",
        foregroundPrimary80: "var(--foreground-primary-80)",
        foregroundPrimary70: "var(--foreground-primary-70)",
        foregroundPrimary60: "var(--foreground-primary-60)",
        foregroundPrimary50: "var(--foreground-primary-50)",
        foregroundPrimary40: "var(--foreground-primary-40)",
        foregroundPrimary30: "var(--foreground-primary-30)",
        foregroundPrimary20: "var(--foreground-primary-20)",
        foregroundPrimary10: "var(--foreground-primary-10)",
        foregroundPrimary0 : "var(--foreground-primary-0)",

        foregroundSecondary: "var(--foreground-secondary)",
        foregroundSecondary90: "var(--foreground-secondary-90)",
        foregroundSecondary80: "var(--foreground-secondary-80)",
        foregroundSecondary70: "var(--foreground-secondary-70)",
        foregroundSecondary60: "var(--foreground-secondary-60)",
        foregroundSecondary50: "var(--foreground-secondary-50)",
        foregroundSecondary40: "var(--foreground-secondary-40)",
        foregroundSecondary30: "var(--foreground-secondary-30)",
        foregroundSecondary20: "var(--foreground-secondary-20)",
        foregroundSecondary10: "var(--foreground-secondary-10)",
        foregroundSecondary0 : "var(--foreground-secondary-0)",
        
        gradientGreen: "var(--gradient-green)",
        gradientPurple: "var(--gradient-purple)",

        dashboardBlue: "var(--dashboard-blue)",
        dashboardBlue90: "var(--dashboard-blue-90)",
        dashboardBlue80: "var(--dashboard-blue-80)",
        dashboardBlue70: "var(--dashboard-blue-70)",
        dashboardBlue60: "var(--dashboard-blue-60)",
        dashboardBlue50: "var(--dashboard-blue-50)",
        dashboardBlue40: "var(--dashboard-blue-40)",
        dashboardBlue30: "var(--dashboard-blue-30)",
        dashboardBlue20: "var(--dashboard-blue-20)",
        dashboardBlue10: "var(--dashboard-blue-10)",
        dashboardBlue0: "var(--dashboard-blue-0)",
      }
    },
  },
  plugins: [],
}
