import './globals.css'
import {useLocale} from 'next-intl'
import {notFound} from 'next/navigation'
import { Sofia_Sans } from 'next/font/google'


import Navbar from './components/Navbar';
import Footer from './components/Footer';

const sofiaSans = Sofia_Sans({ variable: '--font-sofia-sans',subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }) {

  const locale = useLocale();

  if(params.locale !== locale) {
    notFound();
  }


  return (
    <html lang={locale}>
      <body className={`scroll-smooth ${sofiaSans.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
