/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
        backgroundPrimary: "var(--background-primary)",
        backgroundPrimary90: "var(--background-primary-90)",
        backgroundPrimary80: "var(--background-primary-80)",
        backgroundPrimary70: "var(--background-primary-70)",
        backgroundPrimary60: "var(--background-primary-60)",
        backgroundPrimary50: "var(--background-primary-50)",
        backgroundPrimary40: "var(--background-primary-40)",
        backgroundPrimary30: "var(--background-primary-30)",
        backgroundPrimary20: "var(--background-primary-20)",
        backgroundPrimary10: "var(--background-primary-10)",
        backgroundPrimary0 : "var(--background-primary-0)",

        backgroundSecondary: "var(--background-secondary)",
        backgroundSecondary90: "var(--background-secondary-90)",
        backgroundSecondary80: "var(--background-secondary-80)",
        backgroundSecondary70: "var(--background-secondary-70)",
        backgroundSecondary60: "var(--background-secondary-60)",
        backgroundSecondary50: "var(--background-secondary-50)",
        backgroundSecondary40: "var(--background-secondary-40)",
        backgroundSecondary30: "var(--background-secondary-30)",
        backgroundSecondary20: "var(--background-secondary-20)",
        backgroundSecondary10: "var(--background-secondary-10)",
        backgroundSecondary0 : "var(--background-secondary-0)",

        foregroundPrimary: "var(--foreground-primary)",
        foregroundPrimary90: "var(--foreground-primary-90)",
        foregroundPrimary80: "var(--foreground-primary-80)",
        foregroundPrimary70: "var(--foreground-primary-70)",
        foregroundPrimary60: "var(--foreground-primary-60)",
        foregroundPrimary50: "var(--foreground-primary-50)",
        foregroundPrimary40: "var(--foreground-primary-40)",
        foregroundPrimary30: "var(--foreground-primary-30)",
        foregroundPrimary20: "var(--foreground-primary-20)",
        foregroundPrimary10: "var(--foreground-primary-10)",
        foregroundPrimary0 : "var(--foreground-primary-0)",

        foregroundSecondary: "var(--foreground-secondary)",
        foregroundSecondary90: "var(--foreground-secondary-90)",
        foregroundSecondary80: "var(--foreground-secondary-80)",
        foregroundSecondary70: "var(--foreground-secondary-70)",
        foregroundSecondary60: "var(--foreground-secondary-60)",
        foregroundSecondary50: "var(--foreground-secondary-50)",
        foregroundSecondary40: "var(--foreground-secondary-40)",
        foregroundSecondary30: "var(--foreground-secondary-30)",
        foregroundSecondary20: "var(--foreground-secondary-20)",
        foregroundSecondary10: "var(--foreground-secondary-10)",
        foregroundSecondary0 : "var(--foreground-secondary-0)",
        accentPrimary: "var(--accent-primary)",
        accentPrimary90: "var(--accent-primary-90)",
        accentPrimary80: "var(--accent-primary-80)",
        accentPrimary70: "var(--accent-primary-70)",
        accentPrimary60: "var(--accent-primary-60)",
        accentPrimary50: "var(--accent-primary-50)",
        accentPrimary40: "var(--accent-primary-40)",
        accentPrimary30: "var(--accent-primary-30)",
        accentPrimary20: "var(--accent-primary-20)",
        accentPrimary10: "var(--accent-primary-10)",
        accentPrimary0 : "var(--accent-primary-0)",
        accentSecondary: "var(--accent-secondary)",
        accentSecondary90: "var(--accent-secondary-90)",
        accentSecondary80: "var(--accent-secondary-80)",
        accentSecondary70: "var(--accent-secondary-70)",
        accentSecondary60: "var(--accent-secondary-60)",
        accentSecondary50: "var(--accent-secondary-50)",
        accentSecondary40: "var(--accent-secondary-40)",
        accentSecondary30: "var(--accent-secondary-30)",
        accentSecondary20: "var(--accent-secondary-20)",
        accentSecondary10: "var(--accent-secondary-10)",
        accentSecondary0 : "var(--accent-secondary-0)",
        accentThird: "var(--accent-third)",
        accentThird90: "var(--accent-third-90)",
        accentThird80: "var(--accent-third-80)",
        accentThird70: "var(--accent-third-70)",
        accentThird60: "var(--accent-third-60)",
        accentThird50: "var(--accent-third-50)",
        accentThird40: "var(--accent-third-40)",
        accentThird30: "var(--accent-third-30)",
        accentThird20: "var(--accent-third-20)",
        accentThird10: "var(--accent-third-10)",
        accentThird0 : "var(--accent-third-0)",
        accentFourth: "var(--accent-fourth)",
        accentFourth90: "var(--accent-fourth-90)",
        accentFourth80: "var(--accent-fourth-80)",
        accentFourth70: "var(--accent-fourth-70)",
        accentFourth60: "var(--accent-fourth-60)",
        accentFourth50: "var(--accent-fourth-50)",
        accentFourth40: "var(--accent-fourth-40)",
        accentFourth30: "var(--accent-fourth-30)",
        accentFourth20: "var(--accent-fourth-20)",
        accentFourth10: "var(--accent-fourth-10)",
        accentFourth0 : "var(--accent-fourth-0)",
        optionaltPrimary: "var(--optional-primary)",
        optionaltPrimary90: "var(--optional-primary-90)",
        optionaltPrimary80: "var(--optional-primary-80)",
        optionaltPrimary70: "var(--optional-primary-70)",
        optionaltPrimary60: "var(--optional-primary-60)",
        optionaltPrimary50: "var(--optional-primary-50)",
        optionaltPrimary40: "var(--optional-primary-40)",
        optionaltPrimary30: "var(--optional-primary-30)",
        optionaltPrimary20: "var(--optional-primary-20)",
        optionaltPrimary10: "var(--optional-primary-10)",
        optionaltPrimary0 : "var(--optional-primary-0)",
      },
    },
  },
  plugins: [],
}
